version: '3'
services:

  app:
    build: 
      context: .
      dockerfile: ./docker/Dockerfile
    env_file: ./docker/.env
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:alpine
    container_name: secretsanta_db
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=secretsanta
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    restart: always
    hostname: postgres 